language: rust
jobs:
  - os: windows
    before_install: pacman -S mingw-w64-x86_64-gtk3
  - os: linux
    before_install: sudo apt install gtk+3.0 libpango1.0-dev
  - os: osx
    before_install: brew install gtk+3
script: cargo build --release
