
addons:
  homebrew:
    update: true
    packages:
    - gtk+3
    - pygobject3
    - cairo
  apt:
    update: true
    packages:
    - python3-gi-cairo
    - libcairo-gobject2
    - libcairo2-dev
    - libgirepository1.0-dev
    - libatk1.0-0
    - libgtk-3-0

script: travis_wait 30 ./ci.sh

jobs:
  allow_failures:
    - os: windows
  include:
    - os: linux
    - os: osx
    - os: windows
      language: shell
      install:
        - curl https://pyenv.run | bash
        - export PATH="/c/Users/travis/.pyenv/bin:$PATH"
        - eval "$(pyenv init -)"
        - eval "$(pyenv virtualenv-init -)"
      before_script: find / | grep "ci.sh"
      script: ./ci.si



deploy:
  provider: releases
  api_key:
    secure: f2ZoJlfis/84MNHXg238lSMLo9te0zqs+BbjXx4qpO//DX0tg2KslI7gAzvdfJdALrxWI4x0Mc7bnu5XQz4gXod2eDG6j9FsOZQDqeKLEN2jqKo7jtOmPZjZQ5XG32WRuZh095JNQE1nQmN5sYS5ZB5kS/Btei2bjCatwLOkIiBxdz21lT0V3VY/XC1t+wT7Lx8U7uJFcpPOOAbLOY5CoXVs0N+YKghzIRZZyNOOdcd7nRkwcx+Pf4nER8IfJXR4LAEbyOiRufkdydUVprviw5zXunZsm4+ScI+q8RpDGbncXswlVahkAmylVb63g0Of0OQps1NIVdSKL7EGa1nxhg0ynd+YrOyS4KI67SbxvMmOAsTgGJICV7pen0C0OaPtvDsptCnkqIqewqXFRImnwrk9neVB4VNyPw56ebCtwJx3GH/Y9mPwIyDhS1GqDLnBXZqk+sY0EXp37vbVxyRh0AamxswPJ+xoFOQInDB5koLIMZI6IkA6VFhTh5aaO4196O5aJyS2Acf9A6eu4Itf8BLo1gBKEfBe0I5Gj2JI2YAYNfbg/gNlYxRIe8aFZaF3udA2TWjfIfZVaqRHdG83ijTbHsdLHj1SBtCWjnI9TGA3HYRE4QO0sttdu+No8t5xCrZ+IoCngJC6t6yvv8FVPECyRtPO+WdA0eT0aBekXCQ=
  file: dist/*
  file_glob: true
  on:
    repo: tweirtx/streamline-control
    tags: true
  skip_cleanup: true
