language: rust
cache: 
  - cargo
  - yarn
jobs:
  - os: linux
    dist: bionic
    before_install:
      - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - sudo apt update
      - sudo apt install gtk+3.0 libpango1.0-dev libatk1.0-dev libgtk-3-dev nodejs nodejs-dev node-gyp libssl1.0-dev -y
      - git clone --branch v$NVS_VERSION --depth 1 https://github.com/jasongin/nvs ~/.nvs
      - . ~/.nvs/nvs.sh
      - nvs install 10
      - nvs use 10
      - which cargo-make || cargo install cargo-make
  - os: osx
    before_install:
      - which cargo-make || cargo install cargo-make
      - which cargo-bundle || cargo install cargo-bundle
      - nvm install 10
      - nvm use 10
    script: cargo make package
    after_success: mv "target/release/bundle/osx/Streamline Control.app" . && zip -r streamline-control-mac.zip "Streamline Control.app"
script: cargo make build_release
after_success: mv target/release/streamline-control "target/release/streamline-control-$TRAVIS_OS_NAME"
deploy:
  provider: releases
  api_key:
    secure: OxK0jGxxczo4x6JXsMgqI5vyTi22eyybzi9ZIdvLWIhd7tvEHuHmmMFUjsmKPRYkcMFF1Uq5r7AhH1CE9itpHYRn0DDglXpPs1lQqszNmV3cb7QkBcTyYYBPqVw6yydhSBl0bdAUuiAOoaTR+6HXXfb4Ljfq3T1ZJZ/HcO8bihx2vmbmNYW9HuCzdPZgWJjSwPB49gE91+Mjg9nnQD+O8CwioYuH1YBV5LKqiasvpSZjA21w0DLTV//dYdts1sVDNtB9tOu3nL72L/GfmGkcN9kWY533PPYmBQw+xu5ChIB2V4qXkvfKiKUvggjz2IoFMGb7nVNLFihMguVPomjYXP0nc8UV/vIQ3luWv0kbpmpeNSbn6snBLYM+Vd0IzZPkugL7eRicyWOhMdMKgxz7QAznQff+CNHzA/YxZGB7rOAeQTMU11oImYPvwS51c9edzawmVzQ/6cnpx5+Mkue6dtnmuRRgfhKkO1f3vndt8KT3dcgPbVHCChJUBwPRckZ4+hEj+4zOwpDaRhRzsoh4s/xAjooHWr1bc5GGthuf9azDfsgBSaCNKh5tuVSJcx1Qwo+UcFGaPy+hZ+ld2emUPPpDPY4M+3t0oCAJfD/UuqOYSamJLOJZcqVRH/fABMu0S6bxDV6BzFsoyoV4kCz4DHghvYMgx9Wh4v64dGLkLUw=
  file: 
    - target/release/streamline-control-*
    - streamline-control-mac.zip
  file_glob: true
  on:
    repo: bkeeneykid/streamline-control
    tags: true
  skip_cleanup: 'true'
addons:
  homebrew:
    packages:
    - yarn
    - nvm
    update: true
