
install: 
  - curl --url https://win.rustup.rs/x86_64 --output rustup-init.exe
  - rustup-init -y -t wasm32-unknown-unknown --default-toolchain stable-x86_64-pc-windows-msvc
  - RefreshEnv
  - cargo install cargo-make
build_script: cargo make build_release

deploy:
  provider: GitHub
  auth_token:
    secure: X+gpBHIzQp32WcCgCExZOElE64PvA/yvpvM0rTP/P13ysjcXVdl8j29IIM3fmuCm
  artifact: StreamlineControl
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
  force_update: true
  
artifacts:
  - path: "target/release/streamline-control.exe"
    name: "StreamlineControl"
