
install: 
  - curl --url https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe --output rustup-init.exe
  - rustup-init -y -t wasm32-unknown-unknown
  - RefreshEnv # Choco should handle this
 # - rustup install stable 
  - cargo install cargo-make
#install: choco install rust-ms && cargo install cargo-make
build_script: cargo make build_release

deploy:
  provider: GitHub
  auth_token:
    secure: X+gpBHIzQp32WcCgCExZOElE64PvA/yvpvM0rTP/P13ysjcXVdl8j29IIM3fmuCm
  artifact: StreamlineControl
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
  force_update: true
  
artifacts:
  - path: "target/release/streamline-control.exe"
    name: "StreamlineControl"
