install: 
  - curl --url https://win.rustup.rs/x86_64 --output rustup-init.exe
  - rustup-init -y -t wasm32-unknown-unknown --default-toolchain stable-x86_64-pc-windows-msvc
  - choco install yarn nodejs
  - RefreshEnv
  - curl %bonjour_download% -o bonjoursetupsdk.exe
  - bonjoursdksetup.exe /passive
  - cargo install cargo-make  
  - cargo install wasm-pack
build_script: cargo make build_release

deploy:
  provider: GitHub
  auth_token:
    secure: X+gpBHIzQp32WcCgCExZOElE64PvA/yvpvM0rTP/P13ysjcXVdl8j29IIM3fmuCm
  artifact: StreamlineControl
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
  force_update: true
  
artifacts:
  - path: "target/release/streamline-control.exe"
    name: "StreamlineControl"

cache: 
  - frontend/node_modules                        # local npm modules
  - '%LOCALAPPDATA%\Yarn'
  - '%USERPROFILE%\.cargo'
  - target
  - frontend/target



environment:
  bonjour_download:
    secure: FGUW+24q1dSEZfsrV0p8QFADfnmfH2db1+kG6qsTUSL81iK8ihmnqLHc9wcMG1ISRKwsE5GuXZ46py67MXbxBWZCdQcT61NZgg9yuN6hjfZKdUOCXq1/0DddggvLxOrLCJPQmmpevOs+lOTCJW5pDg==

