[package]
name = "streamline-control"
version = "0.0.13"
authors = ["bkeeneykid <bkeeneykid@me.com>"]
edition = "2018"
description = "An event management system for FIRST Tech Challenge Events"

[package.metadata.bundle]
name = "Streamline Control"
identifier = "com.github.streamline-control"

[build-dependencies]
cargo-bundle = "0.4.0"

[dependencies]
druid = "0.6.0"
self_update = "0.16"
webbrowser = "0.5.4"
tokio = { version = "0.2", features = ["macros", "sync", "rt-core"] }
async-std = "1.6"
warp = "0.2"
sqlx = { version = "0.3", default-features = false, features = [ "runtime-tokio", "macros", "sqlite" ] }
port_scanner = "0.1"