[package]
name = "streamline-control"
version = "0.0.13"
authors = ["bkeeneykid <bkeeneykid@me.com>"]
edition = "2018"
description = "An event management system for FIRST Tech Challenge Events"

[package.metadata.bundle]
name = "Streamline Control"
identifier = "com.github.streamline-control"

[dependencies]
druid = "0.6"
tokio = { version = "0.2", features = ["macros", "sync", "rt-core"] }
async-std = "1.6"
warp = "0.2"
diesel = { version = "1.4", features = ["sqlite"] }

rust-embed="5.5"
mime_guess = "2"
self_update = "0.16"
webbrowser = "0.5"
diesel_migrations = "1.4"
port_scanner = "0.1"
app_dirs2 = "2"
flexi_logger = "0.15"
log = "0.4"
simple_logger = "1.6.0"
mime = "0.3.0"