name: Linux

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
              sudo apt update
              sudo apt install gtk+3.0 libpango1.0-dev libatk1.0-dev libgtk-3-dev libssl1.0-dev -y
              which cargo-make || cargo install cargo-make
              cargo install wasm-pack

      - name: Build
        run: cargo make build_release
