name: Windows

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest

    - uses: actions/checkout@v2

    - name: Install dependencies
      run:
        - curl --url https://win.rustup.rs/x86_64 --output rustup-init.exe
        - rustup-init -y -t wasm32-unknown-unknown --default-toolchain stable-x86_64-pc-windows-msvc
        - choco install nodejs
        - RefreshEnv
        - cargo install cargo-make
        - cargo install wasm-pack

    - name: Build release
      run: cargo make build_release

